- frontend/src/App.js
- frontend/src/components/checkboxTermofUse.js
- frontend/src/components/header.js
- frontend/src/pages/CreateCommunity.js
- frontend/src/pages/Login.js
- frontend/src/pages/Register.js
- frontend/src/pages/SelectCommunities.js
- Right now, register leads to a page to join communities with a table of communities. Axios needs user auth to get the list of communities. 
- Next step is to figure out how to pass the user auth token around
> Added register page, table still needs fix, frontend only

- frontend/src/pages/Register.js
Included some basic form validation on the Register.js page.
Set up an axios.post call to the DB to register a User's info, but this isn't working due to reason's discussed in slack. Currently just console.logs on success or error.
> Register User w/ DB

- frontend/src/App.js
- frontend/src/components/header.js
- frontend/src/components/sideNavAccount.js
- frontend/src/pages/AccountSettings.js
- frontend/src/pages/CreateCommunity.js
- frontend/src/pages/EmailSettings.js
- frontend/src/pages/SelectCommunities.js
> Account settings frontend

- frontend/src/App.js
- frontend/src/_variables.sass
- frontend/src/components/communityHomeCard.js
- frontend/src/components/sideNavAccount.js
- frontend/src/components/sideNavCommunity.js
- frontend/src/pages/AccountSettings.js
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/MyCommunities.js
- Added side nav
- Added community home frontend only
- Link community cards to community home
> Portal home frontend

- app/backend/serializers.py
- frontend/src/App.js
- frontend/src/pages/Register.js
- frontend/src/pages/Welcome.js
- Need to add more fields to POST request to add address, phone number, etc.
> Register works but need to add more fields

- app/backend/models.py
- app/backend/serializers.py
Added the updated phone number fields to the `create_superuser` method and to the `UserSerializer`
> update user serializer and superuser

- app/backend/serializers.py
- app/backend/views.py
- frontend/src/pages/MyCommunities.js
Filtering the community query set to show only communities that the logged in User is in.
Also added an `id` field to the serializer to use that as a key in the frontend.
> Display only communities that user is in

- app/backend/models.py
- app/backend/serializers.py
- frontend/src/App.js
- frontend/src/pages/MyCommunities.js
- frontend/src/pages/Register.js
- Fixed register form to include new fields requested by clients:
1) Phone number 2
2) Phone number types
3) Address line 2
4) How did you know this person?
5) How would you like to help? 
6) What skills can you offer?
- Hid password in frontend form
> register-frontend-fix

- app/backend/urls.py
- app/backend/views.py
- frontend/src/components/communityNavbar.js
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/MyCommunities.js
- Redesigned community home page
- Displays community name and description
> Display community data

- frontend/src/App.js
- frontend/src/components/header.js
- frontend/src/pages/Login.js
- frontend/src/pages/Register.js
> Implemented logout

- frontend/package.json
- frontend/src/App.js
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/CreateNewActivity.js
- frontend/yarn.lock
- Run yarn install for the calendar component
> Create new activity frontend workflow

- app/backend/management/commands/generate-fake-data.py
Added a comma to fix the generate-fake-data command!
> Fix generate-fake-data command

- app/backend/serializers.py
- app/backend/urls.py
- app/backend/views.py
Okay this is not fully tested (namely the post/list views), but I think it works! Figured I would push it up so it doesn't block us anymore.
A few things to note:
- All activities are one of either RideActivity (if activity_type='Giving Rides;), MealActivity (if activity_type='Prearing Meals;), or EventActivity (for all other activity_types)
Retrieving a specific Activity will return all fields specific to that activity_type.
Listing all Activities will return only all fields found within the common Activity model.
> Activity API: List, Retrieve, Create

- app/backend/serializers.py
- frontend/src/pages/AccountSettings.js
- frontend/src/pages/CreateCommunity.js
> Display account info

- frontend/src/App.js
- frontend/src/_variables.sass
- frontend/src/index.css
- frontend/src/pages/CalendarPage.js
- frontend/src/pages/CommunityOneMember.js
- frontend/src/pages/CommunityPeople.js
- frontend/src/pages/ForgotPassword.js
Added search feature for community people and one member cards.
> Added view one community member

- app/backend/serializers.py
- app/backend/urls.py
- app/backend/views.py
- frontend/src/pages/CommunityOneMember.js
- frontend/src/pages/CommunityPeople.js
> Added edit and remove user from community

- app/backend/urls.py
- app/backend/views.py
- frontend/src/pages/CommunityAddMember.js
- Fixed bug in member search
- Added sending email invitations to list of emails
> Added send invitation - backend

- frontend/src/pages/CalendarPage.js
> Formatted calendar page

- frontend/src/pages/CalendarPage.js
- Added 'All' option to calendar coordinator dropdown
> Added 'All' option to calendar coordinator dropdown

- frontend/package.json
- frontend/src/App.js
- frontend/src/components/activityPDF.js
- frontend/src/pages/ActivityReport.js
- frontend/src/pages/CommunityHome.js
- frontend/yarn.lock
- Calendar task 11: Activity Report PDF
> Calendar task 11: Activity Report PDF

- app/backend/views.py
- frontend/src/components/activityPDF.js
- frontend/src/pages/CalendarPage.js
- Added calendar filter for volunteer members, activity type, and activity status
> Calendar filter

- app/backend/models.py
- app/backend/serializers.py
- frontend/jsconfig.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/activityPDF.js
- frontend/src/components/header.js
- frontend/src/pages/ActivityReport.js
- frontend/src/pages/CalendarPage.js
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/CreateCommunity.js
- frontend/src/pages/MyCommunities.js
- frontend/src/pages/Register.js
- frontend/src/pages/Welcome.js
- frontend/yarn.lock
- Only admins can create new communities
- Added a dotenv file to store variables
- Fixed registering errors
> Permissions part 1

- app/backend/models.py
- frontend/src/App.js
- frontend/src/components/footer.js
- frontend/src/components/sidebar.js
- frontend/src/pages/CalendarPage.js
- frontend/src/pages/CommunityEdit.js
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/CreateNewActivity.js
- also the footer but lowkey might not be legal
> Edit community - frontend only

- frontend/package.json
- frontend/src/components/communityNavbar.js
- frontend/src/pages/Announcements.js
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/PhotoGallery.js
- frontend/yarn.lock
- Added all things on community home except for photo gallery (need to figure out a good way to display it) and message board (haven't implemented)
> Edit community

- app/backend/models.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/CommunityHome.js
- frontend/src/pages/PhotoGallery.js
> Photo gallery rework

- app/backend/serializers.py
- frontend/src/App.js
- frontend/src/components/sideNavAccount.js
- frontend/src/pages/AccountSettings.js
- frontend/src/pages/ActivityReport.js
- frontend/src/pages/CommunityOneMember.js
- frontend/src/pages/CreateAnnouncement.js
- frontend/src/pages/EmailSettings.js
- frontend/src/pages/MyCommunities.js
- frontend/src/pages/PasswordSettings.js
- Added API call to edit account info
- Separated account information and password settings
> Edit account info

- app/src/App.js
- app/src/components/communityNavbar.js
- app/src/components/sidebar.js
- app/src/pages/ActivityReport.js
- app/src/pages/CommunityHome.js
- app/src/pages/CustomGeneral.js
- app/src/pages/CustomSections.js
- app/src/pages/ManageActivities.js
- app/src/pages/MessageBoard.js
- Changed permissions for custom sections
- Made create custom sections at the top nav bar for easy access
> Added custom sections to top nav bar

- app/src/App.js
- app/src/pages/Register.js
> Fix Register Form not working on deploy

- app/backend/views.py
- app/src/index.css
- app/src/pages/CommunityAddMember.js
- app/src/pages/CommunityPeople.js
- app/src/pages/CreateCommunity.js
- app/src/pages/JoinRequests.js
- app/src/pages/MessageBoard.js
- Changed invite message for inviting new members
- Removed warning from tinymce
- Added admin sidebar to CommunityPeople.js
- Removed "join community" notification at the bottom of create community page
> Update invite members page
